<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHZETGmQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHZETGmQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHZETGmQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHZETGmQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHZETGmQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'HZETGmQ',
    'container.build_id' => '74bb5830',
    'container.build_time' => 1661130149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHZETGmQ');
