<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNFNUn1Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNFNUn1Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNFNUn1Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNFNUn1Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNFNUn1Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'NFNUn1Y',
    'container.build_id' => '484635ac',
    'container.build_time' => 1661110038,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNFNUn1Y');
