<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzURVcf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzURVcf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzURVcf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzURVcf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIzURVcf\App_KernelDevDebugContainer([
    'container.build_hash' => 'IzURVcf',
    'container.build_id' => '652a7861',
    'container.build_time' => 1661107001,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzURVcf');
